language: d
sudo: false

script: dub test -b unittest-cov

# doveralls is currently broken with the latest dub
# see: https://github.com/ColdenCullen/doveralls/pull/21
# 
#after_success:
#  - dub fetch doveralls
#  - dub run doveralls
