name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  quality_actions:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github

  quality_dlang:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
      - run: dub fetch dscanner
      - run: dub run dscanner -- lint

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: dlang-community/setup-dlang@v2
      - run: dub test
