name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - test
    tags:
      - '*'
  workflow_dispatch:

jobs:
  quality_actions:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - run: yamllint .
        working-directory: .github
